---
title: "Codebook for Assigment on Getting and Cleaning data"
author: "Vinayak Shinde"
date: "25-10-2015"
output:
  Readme on the Repo
  Codebook
  FinalAverages.txt
  
---

## Project Description
Aim of the project is to get the training and test data sets from the experiment 
"Human Activity Recognition Using Smartphones Dataset" combine, clean and then analyse them.

##Study design and data processing

###Collection of the raw data
The data represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphone
###Notes on the original (raw) data 
The files of intrest are
the actual observations recorded in  files as X_train and X_test.
The subjects on whom the observations were made are  present in the subject_test and subject_train files
The activity for whom the observations are recorded are present in y_test and y_train files
The decription of the activities are present in the activity_labels files


##Creating the tidy datafile

###Guide to create the tidy data file
1 Down load the files from the link provided(https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)
2 Uncompress them and copy then above mentioned files to your working directory
3: Read the features representing out variables for the observations as a table,Transpose it such that the second row can be used to assign names to the observation table
4: Read the observations from the x_test in a table
5: Assign names from the step 3
6: Read y_test which is nothing but activity codes into a table
7: Read activities into the tables
8: Join the activity codes to activity labeles to get meaning full names for the activities
9: Read the subject_test into a table.
10: Combined the tables in step5, 8 and 9 to get a complete test data set with activity labes and column names
11: Repeat the steps 4 thur 10 for Training dataset
12 Append the data in steps 10 and 11 to create a master data set of training and test observations combined
13: Next find the indices of the columns that contain the mean and std deviation
14: Use those indiced to retain the columns in the master data set of further intrest including the subject, activity code and activity labels
15  Use the subset in step 14 and group on subject, activity code, activity lables and calculate mean of every other column to create a final data set.


###Cleaning of the data
Please refer ReadMe on the repo describes the over all requirement for cleaning the data.
##Description of the variables in the tidy data file
Final gives us a mean for every subject every activity for every variable of intrest.
 It contains 40 rows with 82 columns
 The columns and the data set is described below in detail.
 - Classes 'grouped_df', 'tbl_df', 'tbl' and 'data.frame':	40 obs. of  82 variables:
 $ Subject                        : int  1 2 3 4 4 5 6 6 7 8 ...
 $ ActivityCd                     : int  1 1 1 1 2 1 1 2 2 2 ...
 $ ActivityLabel                  : Factor w/ 6 levels "LAYING","SITTING",..: 4 4 4 4 6 4 4 6 6 6 ...
 $ tBodyAcc-mean()-X              : num  0.266 0.273 0.273 0.277 0.27 ...
 $ tBodyAcc-mean()-Y              : num  -0.0183 -0.0191 -0.0179 -0.0133 -0.0171 ...
 $ tBodyAcc-mean()-Z              : num  -0.108 -0.116 -0.106 -0.106 -0.11 ...
 $ tGravityAcc-mean()-X           : num  0.745 0.661 0.708 0.731 0.667 ...
 $ tGravityAcc-mean()-Y           : num  -0.0826 -0.1472 -0.0261 0.0723 0.1761 ...
 $ tGravityAcc-mean()-Z           : num  0.0723 0.1349 0.0481 0.194 0.117 ...
 $ tBodyAccJerk-mean()-X          : num  0.0771 0.0785 0.0702 0.078 0.0802 ...
 $ tBodyAccJerk-mean()-Y          : num  0.01659 0.00709 0.01447 -0.00103 0.01068 ...
 $ tBodyAccJerk-mean()-Z          : num  -0.009108 0.000756 -0.000527 -0.007371 -0.007379 ...
 $ tBodyGyro-mean()-X             : num  -0.0209 -0.0517 -0.0248 -0.0299 -0.0275 ...
 $ tBodyGyro-mean()-Y             : num  -0.0881 -0.0568 -0.0744 -0.075 -0.0846 ...
 $ tBodyGyro-mean()-Z             : num  0.0863 0.0873 0.0867 0.0957 0.0958 ...
 $ tBodyGyroJerk-mean()-X         : num  -0.0971 -0.0876 -0.0992 -0.1051 -0.1122 ...
 $ tBodyGyroJerk-mean()-Y         : num  -0.0417 -0.0434 -0.0402 -0.0411 -0.0384 ...
 $ tBodyGyroJerk-mean()-Z         : num  -0.0471 -0.0558 -0.0521 -0.0609 -0.053 ...
 $ tBodyAccMag-mean()             : num  -0.454 -0.535 -0.563 -0.638 -0.442 ...
 $ tGravityAccMag-mean()          : num  -0.454 -0.535 -0.563 -0.638 -0.442 ...
 $ tBodyAccJerkMag-mean()         : num  -0.545 -0.588 -0.65 -0.722 -0.552 ...
 $ tBodyGyroMag-mean()            : num  -0.475 -0.615 -0.643 -0.708 -0.574 ...
 $ tBodyGyroJerkMag-mean()        : num  -0.64 -0.747 -0.784 -0.85 -0.771 ...
 $ fBodyAcc-mean()-X              : num  -0.532 -0.574 -0.626 -0.699 -0.518 ...
 $ fBodyAcc-mean()-Y              : num  -0.406 -0.433 -0.502 -0.611 -0.392 ...
 $ fBodyAcc-mean()-Z              : num  -0.596 -0.63 -0.7 -0.785 -0.708 ...
 $ fBodyAcc-meanFreq()-X          : num  -0.181 -0.107 -0.193 -0.156 -0.23 ...
 $ fBodyAcc-meanFreq()-Y          : num  0.0576 0.1057 0.0389 0.052 0.1364 ...
 $ fBodyAcc-meanFreq()-Z          : num  0.05837 0.08721 0.00447 -0.01384 -0.02046 ...
 $ fBodyAccJerk-mean()-X          : num  -0.547 -0.562 -0.646 -0.718 -0.548 ...
 $ fBodyAccJerk-mean()-Y          : num  -0.507 -0.509 -0.583 -0.685 -0.471 ...
 $ fBodyAccJerk-mean()-Z          : num  -0.695 -0.716 -0.78 -0.845 -0.793 ...
 $ fBodyAccJerk-meanFreq()-X      : num  -0.0488 0.0868 -0.0477 0.0388 -0.0627 ...
 $ fBodyAccJerk-meanFreq()-Y      : num  -0.215 -0.14 -0.237 -0.174 -0.19 ...
 $ fBodyAccJerk-meanFreq()-Z      : num  -0.0964 -0.0943 -0.1937 -0.0765 -0.1643 ...
 $ fBodyGyro-mean()-X             : num  -0.623 -0.639 -0.642 -0.708 -0.537 ...
 $ fBodyGyro-mean()-Y             : num  -0.505 -0.722 -0.775 -0.852 -0.799 ...
 $ fBodyGyro-mean()-Z             : num  -0.554 -0.602 -0.671 -0.724 -0.635 ...
 $ fBodyGyro-meanFreq()-X         : num  -0.03203 -0.00577 -0.10257 -0.14535 -0.0762 ...
 $ fBodyGyro-meanFreq()-Y         : num  -0.0902 -0.0702 -0.1677 -0.3576 -0.4033 ...
 $ fBodyGyro-meanFreq()-Z         : num  -0.018 0.0514 -0.0322 -0.0236 0.0996 ...
 $ fBodyAccMag-mean()             : num  -0.478 -0.515 -0.579 -0.668 -0.498 ...
 $ fBodyAccMag-meanFreq()         : num  0.1421 0.1922 0.0771 0.0692 0.1393 ...
 $ fBodyBodyAccJerkMag-mean()     : num  -0.499 -0.51 -0.605 -0.702 -0.529 ...
 $ fBodyBodyAccJerkMag-meanFreq() : num  0.2 0.193 0.112 0.165 0.153 ...
 $ fBodyBodyGyroMag-mean()        : num  -0.535 -0.7 -0.717 -0.785 -0.683 ...
 $ fBodyBodyGyroMag-meanFreq()    : num  0.0649 0.0471 -0.0846 -0.1579 -0.0842 ...
 $ fBodyBodyGyroJerkMag-mean()    : num  -0.646 -0.752 -0.81 -0.868 -0.793 ...
 $ fBodyBodyGyroJerkMag-meanFreq(): num  0.198 0.125 0.06 0.145 0.181 ...
 $ tBodyAcc-std()-X               : num  -0.546 -0.606 -0.623 -0.684 -0.481 ...
 $ tBodyAcc-std()-Y               : num  -0.368 -0.429 -0.48 -0.59 -0.384 ...
 $ tBodyAcc-std()-Z               : num  -0.503 -0.589 -0.654 -0.742 -0.658 ...
 $ tGravityAcc-std()-X            : num  -0.96 -0.963 -0.966 -0.968 -0.955 ...
 $ tGravityAcc-std()-Y            : num  -0.951 -0.96 -0.945 -0.942 -0.941 ...
 $ tGravityAcc-std()-Z            : num  -0.926 -0.945 -0.927 -0.937 -0.949 ...
 $ tBodyAccJerk-std()-X           : num  -0.525 -0.558 -0.635 -0.701 -0.523 ...
 $ tBodyAccJerk-std()-Y           : num  -0.47 -0.492 -0.557 -0.671 -0.447 ...
 $ tBodyAccJerk-std()-Z           : num  -0.717 -0.742 -0.796 -0.86 -0.818 ...
 $ tBodyGyro-std()-X              : num  -0.687 -0.711 -0.699 -0.751 -0.623 ...
 $ tBodyGyro-std()-Y              : num  -0.451 -0.723 -0.763 -0.829 -0.75 ...
 $ tBodyGyro-std()-Z              : num  -0.597 -0.635 -0.709 -0.746 -0.696 ...
 $ tBodyGyroJerk-std()-X          : num  -0.638 -0.672 -0.689 -0.778 -0.638 ...
 $ tBodyGyroJerk-std()-Y          : num  -0.634 -0.784 -0.843 -0.911 -0.888 ...
 $ tBodyGyroJerk-std()-Z          : num  -0.665 -0.675 -0.743 -0.791 -0.682 ...
 $ tBodyAccMag-std()              : num  -0.497 -0.553 -0.591 -0.67 -0.506 ...
 $ tGravityAccMag-std()           : num  -0.497 -0.553 -0.591 -0.67 -0.506 ...
 $ tBodyAccJerkMag-std()          : num  -0.516 -0.512 -0.608 -0.71 -0.548 ...
 $ tBodyGyroMag-std()             : num  -0.5 -0.681 -0.674 -0.749 -0.64 ...
 $ tBodyGyroJerkMag-std()         : num  -0.652 -0.74 -0.804 -0.871 -0.803 ...
 $ fBodyAcc-std()-X               : num  -0.553 -0.62 -0.624 -0.679 -0.469 ...
 $ fBodyAcc-std()-Y               : num  -0.39 -0.465 -0.503 -0.606 -0.422 ...
 $ fBodyAcc-std()-Z               : num  -0.499 -0.601 -0.657 -0.74 -0.66 ...
 $ fBodyAccJerk-std()-X           : num  -0.544 -0.595 -0.658 -0.711 -0.54 ...
 $ fBodyAccJerk-std()-Y           : num  -0.466 -0.509 -0.56 -0.679 -0.459 ...
 $ fBodyAccJerk-std()-Z           : num  -0.738 -0.767 -0.811 -0.872 -0.842 ...
 $ fBodyGyro-std()-X              : num  -0.708 -0.735 -0.719 -0.766 -0.652 ...
 $ fBodyGyro-std()-Y              : num  -0.43 -0.727 -0.759 -0.818 -0.727 ...
 $ fBodyGyro-std()-Z              : num  -0.65 -0.683 -0.751 -0.779 -0.749 ...
 $ fBodyAccMag-std()              : num  -0.59 -0.647 -0.663 -0.725 -0.591 ...
 $ fBodyBodyAccJerkMag-std()      : num  -0.542 -0.519 -0.616 -0.723 -0.577 ...
 $ fBodyBodyGyroMag-std()         : num  -0.567 -0.725 -0.704 -0.769 -0.675 ...
 $ fBodyBodyGyroJerkMag-std()     : num  -0.686 -0.744 -0.81 -0.884 -0.83 ...
 - attr(*, "vars")=List of 2
  ..$ : symbol Subject
  ..$ : symbol ActivityCd
 - attr(*, "drop")= logi TRUE
 - Variables present in the dataset

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

###Variable 1 (repeat this section for all variables in the dataset)
Short description of what the variable describes.

Some information on the variable including:
 - Class of the variable
 - Unique values/levels of the variable
 - Unit of measurement (if no unit of measurement list this as well)
 - In case names follow some schema, describe how entries were constructed (for example time-body-gyroscope-z has 4 levels of descriptors. Describe these 4 levels). 

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

####Notes on variable 1:
If available, some additional notes on the variable not covered elsewehere. If no notes are present leave this section out.

##Sources
Sources you used if any, otherise leave out.

##Annex
If you used any code in the codebook that had the echo=FALSE attribute post this here (make sure you set the results parameter to 'hide' as you do not want the results to show again)